server:
  port: 8081

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.keycloak.url}/realms/${app.keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${app.keycloak.url}/realms/${app.keycloak.realm}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: auth-service
app:
  keycloak:
    url: http://keycloak:8080
    realm: car-aggregator-auth
    token-url: ${app.keycloak.url}/realms/${app.keycloak.realm}/protocol/openid-connect/token
    logout-url: ${app.keycloak.url}/realms/${app.keycloak.realm}/protocol/openid-connect/logout
    client:
      id: auth-service-client
      secret: FiDPXGo4mQKmkRFu8wtDg8IQJ6PdpEU8
