server:
  port: 8084

spring:
  application:
    name: rating-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/rating_db?authSource=admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: rating-service
      service: auth-service
  elastic:
    metrics:
      export:
        host: ${elastic.host}
        enabled: true
        export:
          index: metrics-driver
          auto-create-index: false
          step: 1m
elastic:
  host: http://localhost:9200