server:
  port: 8084

spring:
  application:
    name: rating-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/rating_db?authSource=admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/