server:
  port: 8084

spring:
  application:
    name: rating-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: rating_db