server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - TokenRelay
app:
  keycloak:
    url: http://localhost:8080   # Keycloak server URL
    realm: car-aggregator-auth   # Your Keycloak realm
    client-id: auth-service-client    # Client ID for the resource owner password credentials flow
    client-secret: FiDPXGo4mQKmkRFu8wtDg8IQJ6PdpEU8  # Client secret for the OAuth client
