server:
  port: 8086

spring:
  application:
    name: payment-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: payment_db
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: payment-service
      service: auth-service
  elastic:
    metrics:
      export:
        host: ${elastic.host}
        enabled: true
        export:
          index: metrics-driver
          auto-create-index: false
          step: 1m
elastic:
  host: http://localhost:9200