server:
  port: 8086

spring:
  application:
    name: payment-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: payment_db
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/