server:
  port: 8083
spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5434/driver_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: driver-service
