server:
  port: 8083

spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5435/driver_db_test
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Create and drop the schema for tests
      dialect: org.hibernate.dialect.PostgreSQLDialect
  test:
    # Enable H2 for tests if necessary or use the PostgreSQL test database
    h2:
      console:
        enabled: true
