server:
  port: 8083

spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: localhost:29092