server:
  port: 8085

bing-maps:
  api-key: ${BING_MAPS_API_KEY:}

spring:
  application:
    name: ride-service
  datasource:
    url: jdbc:postgresql://localhost:5438/ride_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: ride-service

stubrunner:
  ids:
    - com.modsen:ride-service-contracts:stubs:0.0.1-SNAPSHOT
  workOffline: true
  repositoryRoot: file:/
