server:
  port: 8085

bing-maps:
  api-key: ${BING_MAPS_API_KEY:}

spring:
  application:
    name: ride-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5438/ride_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
    sender:
      type: web
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: ride-service

stubrunner:
  ids:
    - com.modsen:ride-service-contracts:stubs:0.0.1-SNAPSHOT
  workOffline: true
  repositoryRoot: file:/
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
      elastic:
        enabled: true
        host: http://elasticsearch:9200
    tags:
      application: ride-service
      service: auth-service
  elastic:
    metrics:
      export:
        host: ${elastic.host}
        enabled: true
        export:
          index: metrics-driver
          auto-create-index: false
          step: 1m
elastic:
  host: http://elasticsearch:9200