server:
  port: 8085

bing-maps:
  api-key: ${BING_MAPS_API_KEY:}

spring:
  application:
    name: ride-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
